packages:
  - packages/*
  - apps/*
  - tools

catalog:
  '@inversifyjs/plugin': 0.2.0
  '@inversifyjs/strongly-typed': 2.2.0
  '@suites/doubles.vitest': 3.0.1
  '@suites/unit': 3.0.1
  inversify: 7.10.7
  luxon: 3.7.2
  reflect-metadata: 0.2.2
  stacktracey: 2.1.8
  typeson: 9.0.4
  vitest-mock-extended: 3.1.0
  vitest-when: 0.10.0
  winston: 3.19.0
  zod: 4.2.1
  kysely: 0.28.10
  pg: 8.17.2
  react: 19.2.4
  react-dom: 19.2.4

hoist: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - better-sqlite3
