/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Accounts {
  balance: number;
  closed: boolean;
  deleted: boolean;
  id: string;
  name: string;
  ownerId: string;
  type: string;
}

export interface Roles {
  id: string;
  name: string;
  permissions: Generated<Json>;
  routes: Generated<Json>;
}

export interface UserRoles {
  roleId: string;
  userId: string;
}

export interface Users {
  email: string;
  id: string;
  passwordHash: string;
}

export interface DB {
  accounts: Accounts;
  roles: Roles;
  user_roles: UserRoles;
  users: Users;
}
