export const mockGocardlessData = {
  secretId: 'secret-id',
  secretKey: 'secret-key',
  mockToken: 'the-token',
  mockRefreshedToken: 'the-refreshed-token',
  mockRefreshToken: 'the-refresh-token',
  mockRedirectUrl: 'http://www.yourwebpage.com',
  mockInstututionResponse: {
    id: 'N26_NTSBDEB1',
    name: 'N26 Bank',
    bic: 'NTSBDEB1',
    transaction_total_days: '90',
    countries: [
      'GB',
      'NO',
      'SE',
      'FI',
      'DK',
      'EE',
      'LV',
      'LT',
      'NL',
      'CZ',
      'ES',
      'PL',
      'BE',
      'DE',
      'AT',
      'BG',
      'HR',
      'CY',
      'FR',
      'GR',
      'HU',
      'IS',
      'IE',
      'IT',
      'LI',
      'LU',
      'MT',
      'PT',
      'RO',
      'SK',
      'SI',
    ],
    logo: 'https://cdn-logos.gocardless.com/ais/N26_SANDBOX_NTSBDEB1.png',
    supported_features: [
      'account_selection',
      'business_accounts',
      'card_accounts',
      'private_accounts',
      'separate_continuous_history_consent',
    ],
    identification_codes: [],
    max_access_valid_for_days: '180',
  },
  mockAccountDetailsResponses: {
    foo: {
      account: {
        resourceId: 'foo',
        iban: 'string',
        currency: 'string',
        ownerName: 'string',
        name: 'the name',
        product: 'string',
        cashAccountType: 'string',
        additionalAccountData: {
          secondaryIdentification: 'string',
        },
      },
    },
    bar: {
      account: {
        resourceId: 'bar',
        iban: 'string',
        currency: 'string',
        ownerName: 'string',
        details: 'foo-details',
        name: 'the name',
        product: 'string',
        cashAccountType: 'string',
        additionalAccountData: {
          secondaryIdentification: 'string',
        },
      },
    },
  },
  mockAccountId: 'foo',
  mockBalancesResponse: {
    balances: [
      {
        balanceAmount: {
          amount: '657.49',
          currency: 'string',
        },
        balanceType: 'string',
        referenceDate: '2021-11-22',
      },
      {
        balanceAmount: {
          amount: '185.67',
          currency: 'string',
        },
        balanceType: 'string',
        referenceDate: '2021-11-19',
      },
    ],
  },
  mockTransactions: {
    transactions: {
      booked: [
        {
          transactionId: 'foo',
          debtorName: 'bar',
          transactionAmount: {
            currency: 'GBP',
            amount: '328.18',
          },
          bookingDate: '2024-12-31',
          valueDate: '2020-12-31',
        },
        {
          transactionId: 'bar',
          transactionAmount: {
            currency: 'GVP',
            amount: '947.26',
          },
          bookingDate: '2025-12-01',
          valueDate: '2024-12-01',
        },
      ],
      pending: [
        {
          transactionAmount: {
            currency: 'GBP',
            amount: '99.20',
          },
          valueDate: '2023-12-01',
        },
      ],
    },
    last_updated: '2026-01-17T22:13:39+00:00',
  },
  mockConnectedRequisitionResponse: {
    id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    created: '2025-05-14T11:05:56.276Z',
    redirect: 'http://www.yourwebpage.com',
    status: 'LN',
    institution_id: 'N26_NTSBDEB1',
    agreement: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    reference: 'string',
    accounts: ['foo', 'bar'],
    user_language: 'EN',
    link: 'https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/{$INSTITUTION_ID}',
    ssn: 'string',
    account_selection: false,
    redirect_immediate: false,
  },
  mockRequisitionResponse: {
    id: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    created: '2025-05-14T11:05:56.276Z',
    redirect: 'http://www.yourwebpage.com',
    status: 'CR',
    institution_id: 'string',
    agreement: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
    reference: 'string',
    accounts: [],
    user_language: 'EN',
    link: 'https://ob.gocardless.com/psd2/start/3fa85f64-5717-4562-b3fc-2c963f66afa6/{$INSTITUTION_ID}',
    ssn: 'string',
    account_selection: false,
    redirect_immediate: false,
  },

  mockInstititionsList: [
    {
      id: 'ABNAMRO_ABNAGB2LXXX',
      name: 'ABN AMRO Bank Commercial',
      bic: 'ABNAGB2LXXX',
      transaction_total_days: '540',
      countries: ['GB'],
      logo: 'https://storage.googleapis.com/gc-prd-institution_icons-production/UK/PNG/abnamrobank.png',
      max_access_valid_for_days: '90',
      max_access_valid_for_days_reconfirmation: '730',
    },
    {
      id: 'REVOLUT_REVOGB21',
      name: 'Revolut',
      bic: 'REVOGB21',
      transaction_total_days: '730',
      countries: ['GB'],
      logo: 'https://storage.googleapis.com/gc-prd-institution_icons-production/UK/PNG/revolut.png',
      max_access_valid_for_days: '90',
      max_access_valid_for_days_reconfirmation: '730',
    },
  ],
};
