/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Accounts {
  balance: number;
  closed: string;
  deleted: string;
  description: string | null;
  id: string;
  name: string;
  ownerId: string;
  type: string;
}

export interface BankConnections {
  accounts: string | null;
  bankName: string;
  id: string;
  logo: string;
  ownerId: string;
  requisitionId: string | null;
}

export interface Categories {
  description: string | null;
  id: string;
  name: string;
  ownerId: string | null;
}

export interface OauthTokens {
  created: string;
  expiry: string;
  id: string;
  lastUse: string | null;
  ownerId: string;
  provider: string;
  refreshed: string | null;
  refreshExpiry: string | null;
  refreshToken: string;
  token: string;
}

export interface Roles {
  id: string;
  name: string;
  permissions: Generated<string>;
  routes: Generated<string>;
}

export interface SyncDetails {
  checkpoint: string | null;
  id: string;
  lastSync: string | null;
  ownerId: string;
  provider: string;
}

export interface Transactions {
  accountId: string;
  amount: number;
  categoryId: string | null;
  date: string;
  id: string;
  ownerId: string;
  payee: string;
}

export interface UserRoles {
  roleId: string;
  userId: string;
}

export interface Users {
  email: string;
  id: string;
  passwordHash: string;
}

export interface DB {
  accounts: Accounts;
  bank_connections: BankConnections;
  categories: Categories;
  oauth_tokens: OauthTokens;
  roles: Roles;
  sync_details: SyncDetails;
  transactions: Transactions;
  user_roles: UserRoles;
  users: Users;
}
